2nd home work. all  3 tasks are completed.
js-tasks-ru/js-20201030_ilaltim pull request #4
Opened 2020-11-04 06:59 UTC by chertt007

2020-11-04 07:16 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-04 16:11 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let result = new Array(...arr);
`result` далее по коду программы не переприсваивается, следовательно объявление должно быть через `const`

2020-11-04 16:12 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return result.sort((a, b) => -a.localeCompare(b, ['ru', 'en'], {caseFirst: 'upper'}));
строка 13 дублирует строку 11, за исключением порядка аргументов `a` и `b` - от дубликата нужно избавиться

2020-11-04 16:12 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let result = {}
`result` должен быть объявлен через `const`

2020-11-04 16:13 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let prop in obj) {
`for...in` крайне нежелательный способ итерации по объекту, более подробно обсудим это на следующих занятиях

2020-11-04 16:13 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  let result = {};
`result` - это `const`

2020-11-04 16:14 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-11-04 21:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-06 14:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const result = new Array(...arr);
для того чтобы скопировать массив достаточно просто ипользовать литера `[...arr]`

2020-11-06 14:25 UTC, dosandk approved these changes
good 👍

2020-11-06 14:26 UTC, merged