4th task - notification
js-tasks-ru/js-20201030_ilaltim pull request #7
Opened 2020-11-13 21:53 UTC by chertt007

notificator is done.

2020-11-13 22:43 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-15 10:21 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-15 11:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-15 11:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-15 17:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-15 20:52 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +
пожалуйста перед коммитом проверяйте форматирование в файлах - это хорошая привычка.

2020-11-15 20:53 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +
все эти переводы строк было бы неплохо удалить.

2020-11-15 21:03 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> + show(...args) {
было бы неплохо вынести из этого мтода логику рендера. Другими словами в методе `render` создаем сам элемент компонента. А вот в методе `show` просто его показываем.

2020-11-15 21:03 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> + static elem = null;
отлично что используете статическое свойство

2020-11-15 21:04 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-11-17 08:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-17 11:34 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +   else if (NotificationMessage.elem) {
это `else...if` условие можно заменить просто на `else`

2020-11-17 11:36 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        if (el.images) {
подумайте, возможно этот код можно упростить. По сути эти 2 условия отличаются только наличием шаблона для изображения. Может стоит их объединить?

2020-11-17 11:38 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +      if (sortType === 'number' && orderValue === 'asc') {
Это этих 4х `if`- фов можно избавиться. Алгоритм следующий:
1. нужно определить порядок сортировки: `asc` или `desc` - это позволит избавиться от оператора && в условиях
2. сделать `switch...case` по типам данных: `number`, `string`

2020-11-17 11:39 UTC, dosandk requested changes
Посмотрите комменты в SortableTable - замечания нужно поправить

2020-11-17 21:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
- should be rendered correctly
- should have default sorting marked by arrow icon
- should sort "desc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal number
- should move arrow icon to the corresponding column after sorting
- should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

2020-11-18 22:59 UTC, closed without merging