5Task + 6Task
js-tasks-ru/js-20201030_ilaltim pull request #8
Opened 2020-11-18 23:02 UTC by chertt007

5Task - Notificator + Sortabletable - after review.
6Task - Sortabletable v2. addEventListener.

2020-11-19 00:23 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-19 22:11 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +     args[0].insertAdjacentHTML('afterbegin', this.element.outerHTML);
Почему Вы используете метод `insertAdjacentHTML`?
Можно ли сделать тоже самое с помощью метода `append`?

2020-11-19 22:12 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> + show(...args) {
если задать дефолтное значение для `args` - сможет ли это упростить код?

2020-11-19 22:17 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        const url = el.images ? el.images[0].url : null;
В строке 42 происходит поиск `url` в тернарном операторе (el.images ? ...), обратите внимание что на строке 44 происходит аналогичная проверка (el.images).
Подумайте можно ли свести код только к одной проверке?

2020-11-19 22:19 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        this.data.sort((objA, objB) => {
В строке 77 происходит таже операция сортировки на массиве `data`, только с другой функцией колбека. Подумайте можно ли вынести сортировку на более высокий уровень, на котором решать какой колбек в зависимости от типа данных ей передавать

2020-11-19 22:21 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        const ArrowToRemove = element.querySelector('.sortable-table__sort-arrow');
нельзя именовать переменные с заглавной буквы. С заглавной буквы именуются только классы и функции конструкторы.
Было бы неплохо вынести получение элемента стрелки за пределы обработчика события, чтобы эта операция не выполнялась при каждом срабатывании

2020-11-19 22:22 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        cell.innerHTML = cell.innerHTML + `<span data-element="arrow" class="sortable-table__sort-arrow">
в строке 36 возникнет ошибка, если тернарное выражение в строке 35 вернет `null`

2020-11-19 22:23 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      const sortFn = this.sort.bind(this);
зачем в данной строке происходит `bind`?

2020-11-19 22:24 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        tableBody.innerHTML = `${getBodyBody()}`;
зачем вызов `getBodyBody()` обернут в шаблонную строку?

2020-11-19 22:26 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        this.data.sort((objA, objB) => {
подумайте, можно ли не дублировать вызовы `this.data.sort` для каждого кейса?
Возможно следует вынести функцию сортировки на уровень выше и решать заранее какой колбек передать в зависимости от типа number или string
Посмотрите пожалуйста на решение которое мы разбирали на занятии

2020-11-19 22:27 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        ${el.title && `<div class="sortable-table__cell">${el.title}</div>`}
помните мы разбирали дефолтные параметры функции.
Попробуйте воспользоваться этим приемом и избавиться от проверок в шаблоне типа `this.prop && ...`

2020-11-19 22:29 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.body.addEventListener('pointermove', onMove);
было бы очень неплохо навешивать данный обработчик `pointermove` только при нахождении курсора над элементами с дата атрибутом `tooltip` а после того как курсор выйдет за пределы такого элемента - удалять обработчик

2020-11-19 22:29 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  static linkToRenderFunc = null;
почему эти свойства было решено сделать статическими?

2020-11-19 22:30 UTC, dosandk requested changes
необходимо ответить на вопросы.
внести изменения согласно комментариям

2020-11-19 22:44 UTC, chertt007 commented on 05-dom-document-loading/1-notification/index.js
> +     args[0].insertAdjacentHTML('afterbegin', this.element.outerHTML);
+

2020-11-19 22:45 UTC, chertt007 commented on 05-dom-document-loading/1-notification/index.js
> + show(...args) {
честно говоря не очень понял какое значение по дефолту лучше задать.

2020-11-19 22:49 UTC, chertt007 commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        const url = el.images ? el.images[0].url : null;
+

2020-11-19 23:03 UTC, chertt007 commented on 06-events-practice/2-tooltip/index.js
> +  static linkToRenderFunc = null;
В целом я так понимаю можно было сделать их и не статическими. Мне показалось правильным сделать их статическими потому что мы испольуем singltone и если я правильно понял его идею, то экземпляр класса должен быть один.

2020-11-19 23:08 UTC, chertt007 commented on 06-events-practice/2-tooltip/index.js
> +    document.body.addEventListener('pointermove', onMove);
+

2020-11-19 23:14 UTC, chertt007 commented on 06-events-practice/1-sortable-table-v2/index.js
> +        ${el.title && `<div class="sortable-table__cell">${el.title}</div>`}
Да, конечно помню. Я только не понимаю как это тут применить. Смотрите, если например el.images в элементе нету - то и ячейки не должно быть, получается все равно нужна проверка на каждое поле. Может же быть передано только 2 поля или только 3 поля. что можно по дефолту задать? Тем более я пользуюбсь тут функцией map котороя должна же передать аргумент в функцию колбэк. Возможно я чего то не понял, прошу меня извинить.

2020-11-19 23:15 UTC, chertt007 commented on 06-events-practice/1-sortable-table-v2/index.js
> +        tableBody.innerHTML = `${getBodyBody()}`;
согласен - это лишнее

2020-11-19 23:17 UTC, chertt007 commented on 06-events-practice/1-sortable-table-v2/index.js
> +        const ArrowToRemove = element.querySelector('.sortable-table__sort-arrow');
+

2020-11-19 23:20 UTC, chertt007 commented on 06-events-practice/1-sortable-table-v2/index.js
> +        cell.innerHTML = cell.innerHTML + `<span data-element="arrow" class="sortable-table__sort-arrow">
поставил проверку. спасибо!

2020-11-19 23:21 UTC, chertt007 commented on 05-dom-document-loading/1-notification/index.js
> +     args[0].insertAdjacentHTML('afterbegin', this.element.outerHTML);
исправил, спасибо.

2020-11-19 23:22 UTC, chertt007 commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        const url = el.images ? el.images[0].url : null;
исправил.

2020-11-20 01:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-20 03:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-20 04:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-20 13:36 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> + show(...args) {
`show (root = document.body)` - вот так

2020-11-20 13:37 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        ${el.title && `<div class="sortable-table__cell">${el.title}</div>`}
все хорошо, давайте рассмотрим это на занятии. Я сегодня обращу на это внимание

2020-11-20 13:39 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  static linkToRenderFunc = null;
да, совершенно верно, экземляр будет всегда один, как раз по этому и нет потребности использовать статическое свойство

2020-11-20 20:02 UTC, chertt007 commented on 05-dom-document-loading/1-notification/index.js
> + show(...args) {
поправил.

2020-11-20 20:07 UTC, chertt007 commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        this.data.sort((objA, objB) => {
прошу меня извинить, я уже второй день ломаю голову над этим кейсом и не понимаю, что мне нужно сделать. Может мне не хватает опыта или знаний что бы понять о чем конкретно тут идет речь просто... я могу написать функцию сортировки для стрингов и для намбер по отдельности, но какой в этом смысл?

2020-11-20 20:07 UTC, chertt007 commented on 06-events-practice/1-sortable-table-v2/index.js
> +        const ArrowToRemove = element.querySelector('.sortable-table__sort-arrow');
поправил

2020-11-20 20:18 UTC, chertt007 commented on 06-events-practice/1-sortable-table-v2/index.js
> +      const sortFn = this.sort.bind(this);
я сделал листенер стрелочной функцией примерно как Вы объясняли на уроке. Это очень круто, больше не нужно ничего bind-ить. Просто супер, я первый раз почувствовал как работают arrow function. спасибо что заставляете переделывать , я бы сам себя не заставил)

2020-11-20 20:18 UTC, chertt007 commented on 06-events-practice/2-tooltip/index.js
> +    document.body.addEventListener('pointermove', onMove);
поправил

2020-11-20 20:19 UTC, chertt007 commented on 06-events-practice/1-sortable-table-v2/index.js
> +        ${el.title && `<div class="sortable-table__cell">${el.title}</div>`}
не осилил, извините.

2020-11-20 20:19 UTC, chertt007 commented on 06-events-practice/1-sortable-table-v2/index.js
> +        this.data.sort((objA, objB) => {
Не осилил. написал поробный комент к этой же функции из прошлой домашки выше.

2020-11-20 20:26 UTC, chertt007 commented on 06-events-practice/2-tooltip/index.js
> +  static linkToRenderFunc = null;
Понял, переделал.

2020-11-20 22:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-21 21:35 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +   //this.element = null;
не оставляйте закомментированный код

2020-11-21 21:40 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        this.data.sort((objA, objB) => {
Все что нужно сделать, это просто внутрь `sort` положить конструкцию `switch...case`, это позволит сделать код компактнее и избавиться от дубликатов.
Вот так:
```
    return arr.sort((a, b) => {
      switch (sortType) {
      case 'number':
        return direction * (a[field] - b[field]);
      case 'string':
        return direction * a[field].localeCompare(b[field], 'ru');
      case 'custom':
        return direction * customSorting(a, b);
      default:
        return direction * (a[field] - b[field]);
      }
    });
```

2020-11-21 21:41 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        this.data.sort((objA, objB) => {
хорошо, также оставил коммент выше, посмотрите пожалуйста

2020-11-21 21:42 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        ${el.title && `<div class="sortable-table__cell">${el.title}</div>`}
давайте оставим пока так, чуть позже разберемся с этим

2020-11-21 21:43 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    let element = document.createElement('div');
тут `const`

2020-11-21 21:43 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.body.addEventListener('pointerover', render);
лучше навешивать обработчики на `document` чтобы избежать казусов при применении стилей к `body`

2020-11-21 21:46 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    this.linkToRenderFunc = render;
помните на занятии я показывал прием с `bind` для обработчиков событий.
Лучше делать это в `constructor` по нескольким причинам:
* конструктор выполнится первым и гарантировано выполнить биндинги
* в конструкторе лучше читаются обработчики событий, так как принято располагать конструктор перед остальными методами

2020-11-21 21:46 UTC, dosandk approved these changes
решения принимаются, посмотрите пожалуйста комментарии :mag:

2020-11-21 21:47 UTC, merged